-- This file has been generated by Dungeon Editor 2.2.4

--- level 1 ---

newMap{
	name = "Tutorial",
	width = 32,
	height = 32,
	levelCoord = {0,0,-1},
	ambientTrack = "dungeon",
	tiles = {
		"castle_floor",
		"castle_wall",
		"dungeon_floor",
		"dungeon_floor_tiles",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,4,4,5,5,5,3,3,5,5,5,5,3,3,3,5,5,5,
	5,5,5,5,3,3,3,3,3,3,3,3,3,3,5,4,4,4,3,3,3,3,3,3,3,3,3,5,3,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,4,4,5,5,5,3,3,5,5,5,5,5,3,3,5,5,5,
	5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,5,
	5,5,3,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,5,
	5,5,5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,5,5,5,
	5,5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,4,4,4,5,5,5,
	5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,5,5,4,4,4,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,5,3,5,2,2,5,5,5,5,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,1,2,2,2,5,5,5,5,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,1,1,2,1,1,1,2,5,5,5,5,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,1,1,1,2,1,1,1,2,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,1,1,1,1,1,1,1,1,1,2,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,1,1,1,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,2,1,1,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,5,2,2,2,2,2,2,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,2,2,1,1,1,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,2,1,1,1,1,1,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,2,2,1,1,1,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,2,2,2,2,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
})

spawn("torch_holder",4,11,1,0,"torch_holder_5")
torch_holder_5.controller:setHasTorch(true)
spawn("torch_holder",4,3,0,0,"torch_holder_7")
torch_holder_7.controller:setHasTorch(true)
spawn("starting_location",19,14,3,0,"starting_location")
spawn("torch_holder",5,8,1,0,"torch_holder_6")
torch_holder_6.controller:setHasTorch(true)
spawn("torch_holder",5,6,0,0,"torch_holder_8")
torch_holder_8.controller:setHasTorch(true)
spawn("torch_holder",2,6,3,0,"torch_holder_9")
torch_holder_9.controller:setHasTorch(true)
spawn("torch_holder",2,4,0,0,"torch_holder_10")
torch_holder_10.controller:setHasTorch(true)
spawn("torch_holder",8,3,0,0,"torch_holder_12")
torch_holder_12.socket:addConnector("onRemoveItem", "dungeon_door_iron_barred_1", "open")
torch_holder_12.controller:setHasTorch(true)
spawn("dungeon_alcove",20,4,2,0,"dungeon_alcove_4")
spawn("brass_key",20,4,2,0,"brass_key_1")
dungeon_alcove_4.surface:addItem(brass_key_1.item)
spawn("dungeon_door_iron",22,3,3,0,"dungeon_door_iron_4")
spawn("lock",21,4,1,0,"lock_2")
lock_2.lock:setOpenedBy("brass_key")
lock_2.lock:addConnector("onActivate", "dungeon_door_iron_4", "open")
spawn("turtle",27,8,1,0,"turtle_1")
turtle_1.monster:setAIState("guard")
turtle_1.monster:addConnector("onDie", "dungeon_door_portcullis_6", "open")
spawn("dungeon_wall_text",8,3,2,0,"dungeon_wall_text_2")
dungeon_wall_text_2.walltext:setWallText("You can pick up a torch for further lightning.")
spawn("dungeon_door_iron_barred",8,3,1,0,"dungeon_door_iron_barred_1")
spawn("dungeon_door_portcullis",26,8,3,0,"dungeon_door_portcullis_6")
spawn("castle_ceiling_light",26,7,1,0,"castle_ceiling_light_1")
spawn("castle_ceiling_light",28,9,1,0,"castle_ceiling_light_2")
spawn("castle_ceiling_light",26,9,2,0,"castle_ceiling_light_3")
spawn("castle_ceiling_light",28,7,1,0,"castle_ceiling_light_5")
spawn("torch_holder",20,2,0,0,"torch_holder_11")
torch_holder_11.controller:setHasTorch(true)
spawn("torch_holder",21,4,2,0,"torch_holder_13")
torch_holder_13.controller:setHasTorch(true)
spawn("leather_brigandine",15,4,3,0,"leather_brigandine_1")
spawn("leather_pants",16,4,1,0,"leather_pants_1")
spawn("dungeon_pressure_plate",3,10,3,0,"dungeon_pressure_plate_2")
dungeon_pressure_plate_2.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_2.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_2.floortrigger:addConnector("onActivate", "script_entity_2", "clear")
spawn("script_entity",5,10,2,0,"script_entity_2")
script_entity_2.script:setSource("function clear()\
\9for i=1,4 do\
\9\9print(party.party:getChampionByOrdinal(i):getName())\
\9\9for j=1,32 do\
\9\9\9party.party:getChampion(i):removeItemFromSlot(j);\
\9\9end\
\9end\
\9\
\9local champ1 = party.party:getChampion(1);\
\9local champ2 = party.party:getChampion(2);\
\9local champ3 = party.party:getChampion(3);\
\9local champ4 = party.party:getChampion(4);\
\9\
\9\
\9if(champ1:getClass() == \"barbarian\") then champ1:setEnabled(true) else champ1:setEnabled(false) end;\
\9if(champ2:getClass() == \"barbarian\") then champ2:setEnabled(true) else champ2:setEnabled(false) end;\
\9if(champ3:getClass() == \"barbarian\") then champ3:setEnabled(true) else champ3:setEnabled(false) end;\
\9if(champ4:getClass() == \"barbarian\") then champ4:setEnabled(true) else champ4:setEnabled(false) end;\
\9\
\9hudPrint(champ1:getClass());\
\9hudPrint(champ2:getClass());\
\9hudPrint(champ3:getClass());\
\9hudPrint(champ4:getClass());\
end")
spawn("dungeon_door_portcullis",20,10,2,0,"dungeon_door_portcullis_7")
dungeon_door_portcullis_7.door:setDoorState("open")
spawn("floor_trigger",20,11,1,0,"floor_trigger_1")
floor_trigger_1.floortrigger:setTriggeredByParty(true)
floor_trigger_1.floortrigger:setTriggeredByMonster(false)
floor_trigger_1.floortrigger:setTriggeredByItem(false)
floor_trigger_1.floortrigger:setTriggeredByDigging(false)
floor_trigger_1.floortrigger:setDisableSelf(true)
floor_trigger_1.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_7", "close")
spawn("castle_pillar_light",18,16,0,0,"castle_pillar_light_1")
spawn("castle_pillar_light",18,13,3,0,"castle_pillar_light_2")
spawn("wizard",16,15,1,0,"wizard_1")
wizard_1.brain:disable()
spawn("red_wizard",16,13,1,0,"red_wizard_1")
red_wizard_1.brain:disable()
spawn("castle_ceiling_light",17,14,2,0,"castle_ceiling_light_6")
spawn("castle_ceiling_light",21,13,2,0,"castle_ceiling_light_8")
spawn("script_entity",10,7,0,0,"script_messages")
script_messages.script:setSource("function message1()\
\9GTKGui.Basic.showInfoMessage(\"Welcome to the Legend of Grimrock 2.\\n Press W,S,A,D to walk.\");\
end\
\
function message2()\
\9GTKGui.Basic.showInfoMessage(\"If you want to get dizzy, rotate to the left using 'Q' or to the right using 'E'.\", 5);\
end\
\
function message3()\
\9GTKGui.Basic.showInfoMessage(\"Use the mouse's LEFT CLICK to interact with the environment.\", 5);\
end\
\
function message4()\
\9GTKGui.Basic.showInfoMessage(\"Press '1' to open your inventory.\", 5);\
end\
\
function message5()\
\9GTKGui.Basic.showInfoMessage(\"There are several ways to open a door.\\n This one seems to need a key.\", 5);\
end\
\
function message6()\
\9GTKGui.Basic.showInfoMessage(\"Try to find a button to open this one.\", 5);\
end\
\
function message7()\
\9GTKGui.Basic.showInfoMessage(\"Just pull the chain...\", 5);\
end\
\
\
function message8()\
\9GTKGui.Basic.showInfoMessage(\"To attack use the RIGHT CLICK on the weapon. \\n Don't forget to wield the weapon first.\", 5);\
end")
spawn("grimtk",0,0,2,0,"grimtk_1")
grimtk_1.script:setSource("")
spawn("floor_trigger",3,8,3,0,"floor_trigger_2")
floor_trigger_2.floortrigger:setTriggeredByParty(true)
floor_trigger_2.floortrigger:setTriggeredByMonster(true)
floor_trigger_2.floortrigger:setTriggeredByItem(true)
floor_trigger_2.floortrigger:setTriggeredByDigging(false)
floor_trigger_2.floortrigger:setDisableSelf(true)
floor_trigger_2.floortrigger:addConnector("onActivate", "script_messages", "message2")
spawn("floor_trigger",8,3,0,0,"floor_trigger_3")
floor_trigger_3.floortrigger:setTriggeredByParty(true)
floor_trigger_3.floortrigger:setTriggeredByMonster(true)
floor_trigger_3.floortrigger:setTriggeredByItem(true)
floor_trigger_3.floortrigger:setTriggeredByDigging(false)
floor_trigger_3.floortrigger:setDisableSelf(true)
floor_trigger_3.floortrigger:addConnector("onActivate", "script_messages", "message3")
spawn("floor_trigger",3,12,1,0,"floor_trigger_4")
floor_trigger_4.floortrigger:setTriggeredByParty(true)
floor_trigger_4.floortrigger:setTriggeredByMonster(true)
floor_trigger_4.floortrigger:setTriggeredByItem(true)
floor_trigger_4.floortrigger:setTriggeredByDigging(false)
floor_trigger_4.floortrigger:setDisableSelf(true)
floor_trigger_4.floortrigger:addConnector("onActivate", "script_messages", "message1")
spawn("dungeon_door_portcullis",14,2,1,0,"dungeon_door_portcullis_8")
dungeon_door_portcullis_8.door:setDoorState("open")
spawn("floor_trigger",15,2,0,0,"floor_trigger_5")
floor_trigger_5.floortrigger:setTriggeredByParty(true)
floor_trigger_5.floortrigger:setTriggeredByMonster(true)
floor_trigger_5.floortrigger:setTriggeredByItem(true)
floor_trigger_5.floortrigger:setTriggeredByDigging(false)
floor_trigger_5.floortrigger:setDisableSelf(true)
floor_trigger_5.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_8", "close")
floor_trigger_5.floortrigger:addConnector("onActivate", "script_messages", "message4")
spawn("dungeon_alcove",15,4,2,0,"dungeon_alcove_5")
spawn("leather_boots",15,4,2,0,"leather_boots_2")
dungeon_alcove_5.surface:addItem(leather_boots_2.item)
spawn("leather_cap",15,4,2,0,"leather_cap_2")
dungeon_alcove_5.surface:addItem(leather_cap_2.item)
spawn("dungeon_alcove",16,4,2,0,"dungeon_alcove_6")
spawn("machete",16,4,2,0,"machete_2")
dungeon_alcove_6.surface:addItem(machete_2.item)
spawn("dungeon_pressure_plate",17,3,0,0,"dungeon_pressure_plate_3")
dungeon_pressure_plate_3.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_3.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_3.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_3.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_3.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_3.floortrigger:addConnector("onActivate", "script_entity_1", "check")
spawn("dungeon_door_wooden",18,3,3,0,"dungeon_door_wooden_1")
spawn("script_entity",17,2,2,0,"script_entity_1")
script_entity_1.script:setSource("function check()\
\9local ch = party.party:getChampion(1);\
\9local head = ch:getItem(ItemSlot.Head);\
\9local chest = ch:getItem(ItemSlot.Chest);\
\9local legs = ch:getItem(ItemSlot.Legs);\
\9local feet = ch:getItem(ItemSlot.Feet);\
\9local weapon1 = ch:getItem(ItemSlot.Weapon);\
\9local weapon2 = ch:getItem(ItemSlot.OffHand);\
\9if (head ~= nil and chest ~= nil and legs ~= nil and feet ~= nil) then \
\9\9if(weapon1 == nil and weapon2 ~= nil) then \
\9\9\9if(weapon2:getUiName() == \"Machete\") then openDoor() else message2() end;\
\9\9else \
\9\9\9if(weapon1 ~= nil and weapon2 == nil) then \
\9\9\9\9if(weapon1:getUiName() == \"Machete\") then openDoor() else message2() end; \
\9\9\9else \
\9\9\9if(weapon1 ~= nil and weapon2 ~= nil) then \
\9\9\9\9if(weapon1:getUiName() == \"Machete\" or weapon2:getUiName() == \"Machete\") then openDoor() else message2() end; \
\9\9\9\9else \
\9\9\9\9\9message2()\
\9\9\9\9end\
\9\9\9end\
\9\9end\
\9else \
\9\9message1()\
\9end\
\
end\
\
function message1()\
\9GTKGui.Basic.showInfoMessage(\"You must be fully equiped to pass.\\n Press '1' to open the inventory and LEFT CLICK to pick up objects.\", 8);\
end\
\
function message2()\
\9GTKGui.Basic.showInfoMessage(\"You must have the machete in your hand.\\n Press '1' to open the inventory and LEFT CLICK to pick up objects.\", 8);\
end\
\
function openDoor()\
\9local door = findEntity(\"dungeon_door_wooden_1\");\
\9door.door:open()\
end")
spawn("torch_holder",15,3,3,0,"torch_holder_15")
torch_holder_15.controller:setHasTorch(true)
spawn("floor_trigger",20,3,0,0,"floor_trigger_6")
floor_trigger_6.floortrigger:setTriggeredByParty(true)
floor_trigger_6.floortrigger:setTriggeredByMonster(true)
floor_trigger_6.floortrigger:setTriggeredByItem(true)
floor_trigger_6.floortrigger:setTriggeredByDigging(false)
floor_trigger_6.floortrigger:setDisableSelf(true)
floor_trigger_6.floortrigger:addConnector("onActivate", "script_messages", "message5")
spawn("dungeon_door_iron",24,3,3,0,"dungeon_door_iron_2")
spawn("torch_holder",22,3,0,0,"torch_holder_14")
torch_holder_14.controller:setHasTorch(true)
spawn("torch_holder",24,3,2,0,"torch_holder_16")
torch_holder_16.controller:setHasTorch(true)
spawn("floor_trigger",22,3,2,0,"floor_trigger_7")
floor_trigger_7.floortrigger:setTriggeredByParty(true)
floor_trigger_7.floortrigger:setTriggeredByMonster(true)
floor_trigger_7.floortrigger:setTriggeredByItem(true)
floor_trigger_7.floortrigger:setTriggeredByDigging(false)
floor_trigger_7.floortrigger:setDisableSelf(true)
floor_trigger_7.floortrigger:addConnector("onActivate", "script_messages", "message6")
spawn("floor_trigger",24,3,2,0,"floor_trigger_8")
floor_trigger_8.floortrigger:setTriggeredByParty(true)
floor_trigger_8.floortrigger:setTriggeredByMonster(true)
floor_trigger_8.floortrigger:setTriggeredByItem(true)
floor_trigger_8.floortrigger:setTriggeredByDigging(false)
floor_trigger_8.floortrigger:setDisableSelf(true)
floor_trigger_8.floortrigger:addConnector("onActivate", "script_messages", "message7")
spawn("dungeon_door_iron",26,3,3,0,"dungeon_door_iron_3")
dungeon_door_iron_3.door:setPullChain(true)
spawn("wall_button",23,3,2,0,"wall_button_2")
wall_button_2.button:setDisableSelf(false)
wall_button_2.button:addConnector("onActivate", "dungeon_door_iron_2", "toggle")
spawn("floor_trigger",27,7,1,0,"floor_trigger_9")
floor_trigger_9.floortrigger:setTriggeredByParty(true)
floor_trigger_9.floortrigger:setTriggeredByMonster(true)
floor_trigger_9.floortrigger:setTriggeredByItem(true)
floor_trigger_9.floortrigger:setTriggeredByDigging(false)
floor_trigger_9.floortrigger:setDisableSelf(true)
floor_trigger_9.floortrigger:addConnector("onActivate", "dungeon_door_wooden_2", "close")
floor_trigger_9.floortrigger:addConnector("onActivate", "script_messages", "message8")
spawn("dungeon_door_wooden",27,6,2,0,"dungeon_door_wooden_2")
dungeon_door_wooden_2.door:setDoorState("open")
spawn("floor_trigger",18,14,2,0,"floor_trigger_10")
floor_trigger_10.floortrigger:setTriggeredByParty(true)
floor_trigger_10.floortrigger:setTriggeredByMonster(true)
floor_trigger_10.floortrigger:setTriggeredByItem(true)
floor_trigger_10.floortrigger:setTriggeredByDigging(false)
floor_trigger_10.floortrigger:setDisableSelf(false)
floor_trigger_10.floortrigger:addConnector("onActivate", "script_dialogue_04", "showDemoDialogue")
spawn("script_entity",18,17,0,0,"script_entity_3")
script_entity_3.script:setSource("function move()\
\9\
\9--GameMode.setGameFlag(\"HideGui\", true)\
\9--GameMode.setGameFlag(\"DisableMovement\", true)\
\9--GameMode.setGameFlag(\"DisableMouseLook\", true)\
\9--GameMode.setEnableControls(false)\
\9--party.party:move(3)\
end")
spawn("floor_trigger",16,14,3,0,"floor_trigger_11")
floor_trigger_11.floortrigger:setTriggeredByParty(true)
floor_trigger_11.floortrigger:setTriggeredByMonster(true)
floor_trigger_11.floortrigger:setTriggeredByItem(true)
floor_trigger_11.floortrigger:setTriggeredByDigging(false)
floor_trigger_11.floortrigger:setDisableSelf(false)
floor_trigger_11.floortrigger:addConnector("onActivate", "script_dialogue", "showDemoDialogue")
spawn("script_entity",13,12,2,0,"script_dialogue_01")
script_dialogue_01.script:loadFile("mod_assets/scripts/dialogues/dialogue_01.lua")
spawn("castle_wall_cloth",14,14,3,0,"castle_wall_cloth_1")
spawn("castle_arena_stairs_down",6,20,1,0,"castle_arena_stairs_down_1")
spawn("teleporter",2,20,0,0,"teleporter_1")
teleporter_1.teleporter:setTeleportTarget(1,21,13,0)
teleporter_1.teleporter:setSpin("none")
teleporter_1.teleporter:setTriggeredByParty(true)
teleporter_1.teleporter:setTriggeredByMonster(true)
teleporter_1.teleporter:setTriggeredByItem(true)
teleporter_1.teleporter:setTriggeredBySpell(true)
spawn("script_entity",14,12,0,0,"script_dialogue_02")
script_dialogue_02.script:loadFile("mod_assets/scripts/dialogues/dialogue_02.lua")
spawn("floor_trigger",3,20,3,0,"floor_trigger_12")
floor_trigger_12.floortrigger:setTriggeredByParty(true)
floor_trigger_12.floortrigger:setTriggeredByMonster(true)
floor_trigger_12.floortrigger:setTriggeredByItem(true)
floor_trigger_12.floortrigger:setTriggeredByDigging(false)
floor_trigger_12.floortrigger:setDisableSelf(true)
floor_trigger_12.floortrigger:addConnector("onActivate", "script_dialogue", "setBlueTrue")
spawn("script_entity",15,15,3,0,"script_dialogue")
script_dialogue.script:loadFile("mod_assets/scripts/dialogues/dialogue_wizards.lua")
spawn("castle_ceiling_lantern",4,20,1,0,"castle_ceiling_lantern_1")
spawn("script_entity",1,0,2,0,"script_entity_6")
script_entity_6.script:loadFile("mod_assets/scripts/refresh.lua")
spawn("timer",1,1,1,0,"timer_1")
timer_1.timer:setTimerInterval(1)
timer_1.timer:setDisableSelf(false)
timer_1.timer:setTriggerOnStart(true)
timer_1.timer:setCurrentLevelOnly(false)
timer_1.timer:addConnector("onActivate", "script_entity_6", "refresh")
spawn("script_entity",15,12,3,0,"script_dialogue_03")
script_dialogue_03.script:loadFile("mod_assets/scripts/dialogues/dialogue_03.lua")
spawn("script_entity",16,12,2,0,"script_dialogue_04")
script_dialogue_04.script:loadFile("mod_assets/scripts/dialogues/dialogue_04.lua")

--- level 2 ---

newMap{
	name = "Blue Level",
	width = 32,
	height = 32,
	levelCoord = {0,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,1,1,1,1,1,1,1,1,2,1,1,2,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("dungeon_stairs_up",5,20,3,0,"dungeon_stairs_up_1")
spawn("torch_holder",15,11,0,0,"torch_holder_3")
torch_holder_3.controller:setHasTorch(true)
spawn("dungeon_alcove",15,11,3,0,"dungeon_alcove_1")
spawn("dungeon_wall_broken_01",15,12,3,0,"dungeon_wall_broken_01_4")
spawn("dungeon_door_portcullis",16,12,2,0,"dungeon_door_portcullis_2")
dungeon_door_portcullis_2.door:setPullChain(true)
spawn("torch_holder",18,13,2,0,"torch_holder_1")
torch_holder_1.controller:setHasTorch(true)
spawn("dungeon_wall_broken_01",19,13,0,0,"dungeon_wall_broken_01_3")
spawn("dungeon_wall_broken_02",16,14,2,0,"dungeon_wall_broken_02_4")
spawn("torch_holder",21,14,1,0,"torch_holder_2")
torch_holder_2.controller:setHasTorch(true)
spawn("dungeon_wall_text",21,14,3,0,"dungeon_wall_text_1")
dungeon_wall_text_1.walltext:setWallText("Halls of the Dead")
spawn("dungeon_door_portcullis",21,14,2,0,"dungeon_door_portcullis_1")
dungeon_door_portcullis_1.door:setPullChain(true)
spawn("wall_button",17,16,3,0,"wall_button_1")
wall_button_1.button:setDisableSelf(false)
wall_button_1.button:addConnector("onActivate", "dungeon_door_portcullis_3", "open")
spawn("dungeon_wall_broken_02",22,16,1,0,"dungeon_wall_broken_02_5")
spawn("dungeon_wall_broken_02",13,17,3,0,"dungeon_wall_broken_02_1")
spawn("torch_holder",14,17,2,0,"torch_holder_4")
torch_holder_4.controller:setHasTorch(true)
spawn("dungeon_door_portcullis",15,17,3,0,"dungeon_door_portcullis_3")
dungeon_door_portcullis_3.door:setDoorState("open")
spawn("dungeon_wall_broken_01",15,17,0,0,"dungeon_wall_broken_01_5")
spawn("dungeon_pressure_plate",16,17,3,0,"dungeon_pressure_plate_1")
dungeon_pressure_plate_1.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_1.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_1.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_3", "close")
spawn("ceiling_witch_lantern",17,17,0,0,"ceiling_witch_lantern_3")
spawn("dungeon_alcove",19,17,3,0,"dungeon_alcove_2")
spawn("wooden_box",19,17,3,0,"wooden_box_1")
dungeon_alcove_2.surface:addItem(wooden_box_1.item)
spawn("ceiling_witch_lantern",19,17,1,0,"ceiling_witch_lantern_1")
spawn("dungeon_wall_broken_01",7,19,0,0,"dungeon_wall_broken_01_2")
spawn("ceiling_witch_lantern",7,20,1,0,"ceiling_witch_lantern_7")
spawn("altar",7,20,3,0,"altar_1")
spawn("dungeon_door_iron",11,20,3,0,"dungeon_door_iron_1")
spawn("lock",11,20,0,0,"lock_1")
lock_1.lock:setOpenedBy("iron_key")
lock_1.lock:addConnector("onActivate", "dungeon_door_iron_1", "open")
spawn("ceiling_witch_lantern",18,20,1,0,"ceiling_witch_lantern_4")
spawn("dungeon_secret_button_large",18,20,1,0,"dungeon_secret_button_large_1")
dungeon_secret_button_large_1.button:setDisableSelf(false)
dungeon_secret_button_large_1.button:addConnector("onActivate", "dungeon_secret_door_1", "open")
spawn("ceiling_witch_lantern",20,20,3,0,"ceiling_witch_lantern_2")
spawn("dungeon_wall_broken_01",10,21,2,0,"dungeon_wall_broken_01_1")
spawn("dungeon_wall_broken_02",12,21,2,0,"dungeon_wall_broken_02_2")
spawn("ceiling_witch_lantern",14,21,3,0,"ceiling_witch_lantern_5")
spawn("dungeon_secret_door",20,21,0,0,"dungeon_secret_door_1")
spawn("dungeon_wall_broken_02",15,22,1,0,"dungeon_wall_broken_02_3")
spawn("ceiling_witch_lantern",14,23,2,0,"ceiling_witch_lantern_6")
spawn("dungeon_alcove",14,23,0,0,"dungeon_alcove_3")
spawn("iron_key",14,23,0,0,"iron_key_1")
dungeon_alcove_3.surface:addItem(iron_key_1.item)
spawn("floor_trigger",20,11,0,0,"floor_trigger_14")
floor_trigger_14.floortrigger:setTriggeredByParty(true)
floor_trigger_14.floortrigger:setTriggeredByMonster(true)
floor_trigger_14.floortrigger:setTriggeredByItem(true)
floor_trigger_14.floortrigger:setTriggeredByDigging(false)
floor_trigger_14.floortrigger:setDisableSelf(false)
floor_trigger_14.floortrigger:addConnector("onActivate", "script_entity_4", "deactivateTeleport")
spawn("script_entity",20,10,0,0,"script_entity_4")
script_entity_4.script:setSource("function deactivateTeleport()\
\9findEntity(\"teleporter_blue\"):destroy()\
end")

--- level 3 ---

newMap{
	name = "Red Level",
	width = 32,
	height = 32,
	levelCoord = {1,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,1,1,1,1,1,1,1,1,2,1,1,2,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("torch_holder",18,13,2,0,"torch_holder_17")
torch_holder_17.controller:setHasTorch(true)
spawn("torch_holder",15,11,0,0,"torch_holder_18")
torch_holder_18.controller:setHasTorch(true)
spawn("torch_holder",21,14,1,0,"torch_holder_19")
torch_holder_19.controller:setHasTorch(true)
spawn("torch_holder",14,17,2,0,"torch_holder_20")
torch_holder_20.controller:setHasTorch(true)
spawn("dungeon_alcove",15,11,3,0,"dungeon_alcove_7")
spawn("dungeon_alcove",14,23,0,0,"dungeon_alcove_8")
spawn("iron_key",14,23,0,0,"iron_key_2")
dungeon_alcove_8.surface:addItem(iron_key_2.item)
spawn("dungeon_alcove",19,17,3,0,"dungeon_alcove_9")
spawn("wooden_box",19,17,3,0,"wooden_box_2")
dungeon_alcove_9.surface:addItem(wooden_box_2.item)
spawn("dungeon_wall_text",21,14,3,0,"dungeon_wall_text_3")
dungeon_wall_text_3.walltext:setWallText("Halls of the Dead")
spawn("dungeon_door_portcullis",16,12,2,0,"dungeon_door_portcullis_4")
dungeon_door_portcullis_4.door:setPullChain(true)
spawn("dungeon_door_portcullis",21,15,0,0,"dungeon_door_portcullis_5")
dungeon_door_portcullis_5.door:setPullChain(true)
spawn("dungeon_door_portcullis",14,17,1,0,"dungeon_door_portcullis_9")
dungeon_door_portcullis_9.door:setDoorState("open")
spawn("dungeon_door_iron",11,20,3,0,"dungeon_door_iron_5")
spawn("ceiling_witch_lantern",17,17,0,0,"ceiling_witch_lantern_8")
spawn("ceiling_witch_lantern",19,17,3,0,"ceiling_witch_lantern_9")
spawn("ceiling_witch_lantern",18,20,0,0,"ceiling_witch_lantern_10")
spawn("ceiling_witch_lantern",20,20,1,0,"ceiling_witch_lantern_11")
spawn("ceiling_witch_lantern",14,21,1,0,"ceiling_witch_lantern_12")
spawn("ceiling_witch_lantern",14,23,2,0,"ceiling_witch_lantern_13")
spawn("dungeon_secret_door",20,21,0,0,"dungeon_secret_door_2")
spawn("dungeon_secret_button_large",18,20,1,0,"dungeon_secret_button_large_2")
dungeon_secret_button_large_2.button:setDisableSelf(false)
dungeon_secret_button_large_2.button:addConnector("onActivate", "dungeon_secret_door_2", "open")
spawn("wall_button",17,16,3,0,"wall_button_3")
wall_button_3.button:setDisableSelf(false)
wall_button_3.button:addConnector("onActivate", "dungeon_door_portcullis_9", "open")
spawn("dungeon_pressure_plate",16,17,3,0,"dungeon_pressure_plate_4")
dungeon_pressure_plate_4.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_4.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_4.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_9", "close")
spawn("lock",11,20,0,0,"lock_3")
lock_3.lock:setOpenedBy("iron_key")
lock_3.lock:addConnector("onActivate", "dungeon_door_iron_5", "open")
spawn("dungeon_wall_broken_01",7,19,0,0,"dungeon_wall_broken_01_6")
spawn("dungeon_wall_broken_01",10,21,2,0,"dungeon_wall_broken_01_7")
spawn("dungeon_wall_broken_01",15,12,3,0,"dungeon_wall_broken_01_8")
spawn("dungeon_wall_broken_01",19,13,0,0,"dungeon_wall_broken_01_9")
spawn("dungeon_wall_broken_02",16,14,2,0,"dungeon_wall_broken_02_6")
spawn("dungeon_wall_broken_02",22,16,1,0,"dungeon_wall_broken_02_7")
spawn("dungeon_wall_broken_02",13,17,3,0,"dungeon_wall_broken_02_8")
spawn("dungeon_wall_broken_01",15,17,0,0,"dungeon_wall_broken_01_10")
spawn("dungeon_wall_broken_02",12,21,2,0,"dungeon_wall_broken_02_9")
spawn("dungeon_wall_broken_02",15,22,1,0,"dungeon_wall_broken_02_10")
spawn("ceiling_witch_lantern",7,20,3,0,"ceiling_witch_lantern_14")
spawn("altar",7,20,3,0,"altar_2")
spawn("dungeon_stairs_up",5,20,3,0,"dungeon_stairs_up_2")
spawn("floor_trigger",20,11,3,0,"floor_trigger_15")
floor_trigger_15.floortrigger:setTriggeredByParty(true)
floor_trigger_15.floortrigger:setTriggeredByMonster(true)
floor_trigger_15.floortrigger:setTriggeredByItem(true)
floor_trigger_15.floortrigger:setTriggeredByDigging(false)
floor_trigger_15.floortrigger:setDisableSelf(false)
floor_trigger_15.floortrigger:addConnector("onActivate", "script_entity_5", "deactivateTeleport")
spawn("script_entity",20,10,3,0,"script_entity_5")
script_entity_5.script:setSource("function deactivateTeleport()\
\9findEntity(\"teleporter_red\"):destroy()\
end")

--- level 4 ---

newMap{
	name = "Red Exit",
	width = 32,
	height = 32,
	levelCoord = {1,0,-1},
	ambientTrack = "dungeon",
	tiles = {
		"castle_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("castle_stairs_down",6,20,1,0,"castle_stairs_down_1")
spawn("castle_ceiling_lantern",4,20,0,0,"castle_ceiling_lantern_2")
spawn("teleporter",2,20,3,0,"teleporter_2")
teleporter_2.teleporter:setTeleportTarget(1,21,13,0)
teleporter_2.teleporter:setSpin("none")
teleporter_2.teleporter:setTriggeredByParty(true)
teleporter_2.teleporter:setTriggeredByMonster(true)
teleporter_2.teleporter:setTriggeredByItem(true)
teleporter_2.teleporter:setTriggeredBySpell(true)
spawn("floor_trigger",3,20,2,0,"floor_trigger_13")
floor_trigger_13.floortrigger:setTriggeredByParty(true)
floor_trigger_13.floortrigger:setTriggeredByMonster(true)
floor_trigger_13.floortrigger:setTriggeredByItem(true)
floor_trigger_13.floortrigger:setTriggeredByDigging(false)
floor_trigger_13.floortrigger:setDisableSelf(false)
floor_trigger_13.floortrigger:addConnector("onActivate", "script_dialogue", "setRedTrue")
