-- This file has been generated by Dungeon Editor 2.2.4

--- level 1 ---

newMap{
	name = "Tutorial",
	width = 32,
	height = 32,
	levelCoord = {0,0,-1},
	ambientTrack = "dungeon",
	tiles = {
		"castle_floor",
		"castle_wall",
		"dungeon_floor",
		"dungeon_floor_tiles",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,4,4,5,5,5,4,4,5,5,5,5,3,3,3,3,3,5,
	5,5,5,5,3,3,3,3,3,3,3,5,5,5,5,4,4,4,4,4,4,4,3,3,3,3,3,5,5,5,3,5,
	5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,4,4,5,5,5,4,4,5,5,5,5,5,3,3,3,3,5,
	5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,5,
	5,5,3,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,5,
	5,5,5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,5,5,5,
	5,5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,5,5,5,
	5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,5,4,4,4,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,3,3,3,5,5,5,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,3,5,5,5,5,
	5,5,3,3,3,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,1,1,1,2,5,5,3,3,3,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,1,1,1,1,1,1,1,1,1,1,4,4,4,3,3,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,1,1,1,2,1,1,1,2,5,5,3,4,4,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,2,1,1,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,5,2,2,2,2,2,2,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,5,5,5,5,5,
	5,2,2,1,1,1,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,2,1,1,1,1,1,2,5,5,5,5,5,5,5,3,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,2,2,1,1,1,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,2,2,2,2,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
	5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
})

spawn("torch_holder",4,11,1,0,"torch_holder_5")
torch_holder_5.controller:setHasTorch(true)
spawn("torch_holder",4,3,0,0,"torch_holder_7")
torch_holder_7.controller:setHasTorch(true)
spawn("torch_holder",5,8,1,0,"torch_holder_6")
torch_holder_6.controller:setHasTorch(true)
spawn("torch_holder",5,6,0,0,"torch_holder_8")
torch_holder_8.controller:setHasTorch(true)
spawn("torch_holder",2,6,3,0,"torch_holder_9")
torch_holder_9.controller:setHasTorch(true)
spawn("torch_holder",2,4,0,0,"torch_holder_10")
torch_holder_10.controller:setHasTorch(true)
spawn("torch_holder",8,3,0,0,"torch_holder_12")
torch_holder_12.socket:addConnector("onRemoveItem", "dungeon_door_iron_barred_1", "open")
torch_holder_12.controller:setHasTorch(true)
spawn("dungeon_alcove",20,4,2,0,"dungeon_alcove_4")
spawn("brass_key",20,4,2,0,"brass_key_1")
dungeon_alcove_4.surface:addItem(brass_key_1.item)
spawn("dungeon_door_iron",22,3,3,0,"dungeon_door_iron_4")
spawn("turtle",27,8,1,0,"turtle_1")
turtle_1.monster:setAIState("guard")
turtle_1.monster:addConnector("onDie", "dungeon_door_portcullis_6", "open")
spawn("dungeon_wall_text",8,3,2,0,"dungeon_wall_text_2")
dungeon_wall_text_2.walltext:setWallText("You can pick up a torch for further lightning. Be careful, they can run out of flames.")
spawn("dungeon_door_iron_barred",8,3,1,0,"dungeon_door_iron_barred_1")
spawn("dungeon_door_portcullis",26,8,3,0,"dungeon_door_portcullis_6")
spawn("torch_holder",20,2,0,0,"torch_holder_11")
torch_holder_11.controller:setHasTorch(true)
spawn("torch_holder",21,4,2,0,"torch_holder_13")
torch_holder_13.controller:setHasTorch(true)
spawn("leather_brigandine",15,4,3,0,"leather_brigandine_1")
spawn("leather_pants",16,4,1,0,"leather_pants_1")
spawn("script_entity",5,10,2,0,"script_entity_2")
script_entity_2.script:setSource("function clear()\
\9for i=1,4 do\
\9\9print(party.party:getChampionByOrdinal(i):getName())\
\9\9for j=1,32 do\
\9\9\9party.party:getChampion(i):removeItemFromSlot(j);\
\9\9end\
\9end\
\9\
\9local champ1 = party.party:getChampion(1);\
\9local champ2 = party.party:getChampion(2);\
\9local champ3 = party.party:getChampion(3);\
\9local champ4 = party.party:getChampion(4);\
\9\
\9\
\9if(champ1:getClass() == \"barbarian\") then champ1:setEnabled(true) else champ1:setEnabled(false) end;\
\9if(champ2:getClass() == \"barbarian\") then champ2:setEnabled(true) else champ2:setEnabled(false) end;\
\9if(champ3:getClass() == \"barbarian\") then champ3:setEnabled(true) else champ3:setEnabled(false) end;\
\9if(champ4:getClass() == \"barbarian\") then champ4:setEnabled(true) else champ4:setEnabled(false) end;\
\9\
\9hudPrint(champ1:getClass());\
\9hudPrint(champ2:getClass());\
\9hudPrint(champ3:getClass());\
\9hudPrint(champ4:getClass());\
end")
spawn("floor_trigger",22,14,1,0,"floor_trigger_1")
floor_trigger_1.floortrigger:setTriggeredByParty(true)
floor_trigger_1.floortrigger:setTriggeredByMonster(false)
floor_trigger_1.floortrigger:setTriggeredByItem(false)
floor_trigger_1.floortrigger:setTriggeredByDigging(false)
floor_trigger_1.floortrigger:setDisableSelf(true)
floor_trigger_1.floortrigger:addConnector("onActivate", "castle_door_portcullis_1", "close")
floor_trigger_1.floortrigger:addConnector("onActivate", "script_messages", "message11")
floor_trigger_1.floortrigger:addConnector("onActivate", "script_entity_3", "hook")
spawn("castle_pillar_light",18,16,0,0,"castle_pillar_light_1")
spawn("wizard",16,15,1,0,"wizard_1")
wizard_1.brain:disable()
spawn("castle_ceiling_light",17,14,2,0,"castle_ceiling_light_6")
spawn("castle_ceiling_light",21,14,2,0,"castle_ceiling_light_8")
spawn("script_entity",0,2,0,0,"script_messages")
script_messages.script:loadFile("mod_assets/scripts/messages.lua")
spawn("floor_trigger",3,8,3,0,"floor_trigger_2")
floor_trigger_2.floortrigger:setTriggeredByParty(true)
floor_trigger_2.floortrigger:setTriggeredByMonster(false)
floor_trigger_2.floortrigger:setTriggeredByItem(false)
floor_trigger_2.floortrigger:setTriggeredByDigging(false)
floor_trigger_2.floortrigger:setDisableSelf(true)
floor_trigger_2.floortrigger:addConnector("onActivate", "script_messages", "message2")
spawn("floor_trigger",8,3,0,0,"floor_trigger_3")
floor_trigger_3.floortrigger:setTriggeredByParty(true)
floor_trigger_3.floortrigger:setTriggeredByMonster(false)
floor_trigger_3.floortrigger:setTriggeredByItem(false)
floor_trigger_3.floortrigger:setTriggeredByDigging(false)
floor_trigger_3.floortrigger:setDisableSelf(true)
floor_trigger_3.floortrigger:addConnector("onActivate", "script_messages", "message3")
spawn("floor_trigger",3,12,1,0,"floor_trigger_4")
floor_trigger_4.floortrigger:setTriggeredByParty(true)
floor_trigger_4.floortrigger:setTriggeredByMonster(false)
floor_trigger_4.floortrigger:setTriggeredByItem(false)
floor_trigger_4.floortrigger:setTriggeredByDigging(false)
floor_trigger_4.floortrigger:setDisableSelf(true)
floor_trigger_4.floortrigger:addConnector("onActivate", "script_messages", "message1")
spawn("dungeon_door_portcullis",14,2,1,0,"dungeon_door_portcullis_8")
dungeon_door_portcullis_8.door:setDoorState("open")
spawn("floor_trigger",15,2,0,0,"floor_trigger_5")
floor_trigger_5.floortrigger:setTriggeredByParty(true)
floor_trigger_5.floortrigger:setTriggeredByMonster(false)
floor_trigger_5.floortrigger:setTriggeredByItem(false)
floor_trigger_5.floortrigger:setTriggeredByDigging(false)
floor_trigger_5.floortrigger:setDisableSelf(true)
floor_trigger_5.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_8", "close")
floor_trigger_5.floortrigger:addConnector("onActivate", "script_messages", "message4")
spawn("dungeon_alcove",15,4,2,0,"dungeon_alcove_5")
spawn("leather_boots",15,4,2,0,"leather_boots_2")
dungeon_alcove_5.surface:addItem(leather_boots_2.item)
spawn("leather_cap",15,4,2,0,"leather_cap_2")
dungeon_alcove_5.surface:addItem(leather_cap_2.item)
spawn("dungeon_alcove",16,4,2,0,"dungeon_alcove_6")
spawn("machete",16,4,2,0,"machete_2")
dungeon_alcove_6.surface:addItem(machete_2.item)
spawn("dungeon_pressure_plate",17,3,0,0,"dungeon_pressure_plate_3")
dungeon_pressure_plate_3.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_3.floortrigger:setTriggeredByMonster(false)
dungeon_pressure_plate_3.floortrigger:setTriggeredByItem(false)
dungeon_pressure_plate_3.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_3.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_3.floortrigger:addConnector("onActivate", "script_entity_1", "check")
spawn("dungeon_door_wooden",18,3,3,0,"dungeon_door_wooden_1")
spawn("script_entity",17,2,2,0,"script_entity_1")
script_entity_1.script:setSource("function check()\
\9local ch = party.party:getChampionByOrdinal(1);\
\9local head = ch:getItem(ItemSlot.Head);\
\9local chest = ch:getItem(ItemSlot.Chest);\
\9local legs = ch:getItem(ItemSlot.Legs);\
\9local feet = ch:getItem(ItemSlot.Feet);\
\9local weapon1 = ch:getItem(ItemSlot.Weapon);\
\9local weapon2 = ch:getItem(ItemSlot.OffHand);\
\9if (head ~= nil and chest ~= nil and legs ~= nil and feet ~= nil) then \
\9\9if(weapon1 == nil and weapon2 ~= nil) then \
\9\9\9if(weapon2:getUiName() == \"Machete\") then openDoor() else message2() end;\
\9\9else \
\9\9\9if(weapon1 ~= nil and weapon2 == nil) then \
\9\9\9\9if(weapon1:getUiName() == \"Machete\") then openDoor() else message2() end; \
\9\9\9else \
\9\9\9if(weapon1 ~= nil and weapon2 ~= nil) then \
\9\9\9\9if(weapon1:getUiName() == \"Machete\" or weapon2:getUiName() == \"Machete\") then openDoor() else message2() end; \
\9\9\9\9else \
\9\9\9\9\9message2()\
\9\9\9\9end\
\9\9\9end\
\9\9end\
\9else \
\9\9message1()\
\9end\
\
end\
\
function message1()\
\9GTKGui.Basic.showInfoMessage(\"You must be fully equiped to pass.\\n Press '1' to open the inventory and LEFT CLICK to pick up objects.\", 8);\
end\
\
function message2()\
\9GTKGui.Basic.showInfoMessage(\"You must have the machete in your hand.\\n Press '1' to open the inventory and LEFT CLICK to pick up objects.\", 8);\
end\
\
function openDoor()\
\9local door = findEntity(\"dungeon_door_wooden_1\");\
\9door.door:open()\
end")
spawn("torch_holder",15,3,3,0,"torch_holder_15")
torch_holder_15.controller:setHasTorch(true)
spawn("floor_trigger",20,3,0,0,"floor_trigger_6")
floor_trigger_6.floortrigger:setTriggeredByParty(true)
floor_trigger_6.floortrigger:setTriggeredByMonster(false)
floor_trigger_6.floortrigger:setTriggeredByItem(false)
floor_trigger_6.floortrigger:setTriggeredByDigging(false)
floor_trigger_6.floortrigger:setDisableSelf(true)
floor_trigger_6.floortrigger:addConnector("onActivate", "script_messages", "message5")
spawn("dungeon_door_iron",24,3,3,0,"dungeon_door_iron_2")
spawn("torch_holder",22,3,0,0,"torch_holder_14")
torch_holder_14.controller:setHasTorch(true)
spawn("torch_holder",24,3,2,0,"torch_holder_16")
torch_holder_16.controller:setHasTorch(true)
spawn("floor_trigger",22,3,2,0,"floor_trigger_7")
floor_trigger_7.floortrigger:setTriggeredByParty(true)
floor_trigger_7.floortrigger:setTriggeredByMonster(false)
floor_trigger_7.floortrigger:setTriggeredByItem(false)
floor_trigger_7.floortrigger:setTriggeredByDigging(false)
floor_trigger_7.floortrigger:setDisableSelf(true)
floor_trigger_7.floortrigger:addConnector("onActivate", "script_messages", "message6")
spawn("floor_trigger",24,3,2,0,"floor_trigger_8")
floor_trigger_8.floortrigger:setTriggeredByParty(true)
floor_trigger_8.floortrigger:setTriggeredByMonster(false)
floor_trigger_8.floortrigger:setTriggeredByItem(false)
floor_trigger_8.floortrigger:setTriggeredByDigging(false)
floor_trigger_8.floortrigger:setDisableSelf(true)
floor_trigger_8.floortrigger:addConnector("onActivate", "script_messages", "message7")
spawn("dungeon_door_iron",26,3,3,0,"dungeon_door_iron_3")
dungeon_door_iron_3.door:setPullChain(true)
spawn("wall_button",23,3,2,0,"wall_button_2")
wall_button_2.button:setDisableSelf(false)
wall_button_2.button:addConnector("onActivate", "dungeon_door_iron_2", "toggle")
spawn("floor_trigger",27,7,1,0,"floor_trigger_9")
floor_trigger_9.floortrigger:setTriggeredByParty(true)
floor_trigger_9.floortrigger:setTriggeredByMonster(false)
floor_trigger_9.floortrigger:setTriggeredByItem(false)
floor_trigger_9.floortrigger:setTriggeredByDigging(false)
floor_trigger_9.floortrigger:setDisableSelf(true)
floor_trigger_9.floortrigger:addConnector("onActivate", "dungeon_door_wooden_2", "close")
floor_trigger_9.floortrigger:addConnector("onActivate", "script_messages", "message8")
spawn("dungeon_door_wooden",27,6,2,0,"dungeon_door_wooden_2")
dungeon_door_wooden_2.door:setDoorState("open")
spawn("floor_trigger",17,15,3,0,"floor_trigger_11")
floor_trigger_11.floortrigger:setTriggeredByParty(true)
floor_trigger_11.floortrigger:setTriggeredByMonster(false)
floor_trigger_11.floortrigger:setTriggeredByItem(false)
floor_trigger_11.floortrigger:setTriggeredByDigging(false)
floor_trigger_11.floortrigger:setDisableSelf(false)
floor_trigger_11.floortrigger:addConnector("onActivate", "script_dialogue", "showDemoDialogue")
spawn("script_entity",13,12,2,0,"script_dialogue_01")
script_dialogue_01.script:loadFile("mod_assets/scripts/dialogues/dialogue_01.lua")
spawn("castle_wall_cloth",14,14,3,0,"castle_wall_cloth_1")
spawn("castle_arena_stairs_down",6,20,1,0,"castle_arena_stairs_down_1")
spawn("teleporter",2,20,0,0,"teleporter_1")
teleporter_1.teleporter:setTeleportTarget(1,21,13,0)
teleporter_1.teleporter:setSpin("none")
teleporter_1.teleporter:setTriggeredByParty(true)
teleporter_1.teleporter:setTriggeredByMonster(true)
teleporter_1.teleporter:setTriggeredByItem(true)
teleporter_1.teleporter:setTriggeredBySpell(true)
spawn("script_entity",14,12,0,0,"script_dialogue_02")
script_dialogue_02.script:loadFile("mod_assets/scripts/dialogues/dialogue_02.lua")
spawn("floor_trigger",3,20,3,0,"floor_trigger_12")
floor_trigger_12.floortrigger:setTriggeredByParty(true)
floor_trigger_12.floortrigger:setTriggeredByMonster(false)
floor_trigger_12.floortrigger:setTriggeredByItem(false)
floor_trigger_12.floortrigger:setTriggeredByDigging(false)
floor_trigger_12.floortrigger:setDisableSelf(true)
floor_trigger_12.floortrigger:addConnector("onActivate", "script_dialogue", "setBlueTrue")
floor_trigger_12.floortrigger:addConnector("onActivate", "castle_door_portcullis_3", "close")
floor_trigger_12.floortrigger:addConnector("onActivate", "script_entity_10", "unHook")
spawn("script_entity",15,13,3,0,"script_dialogue")
script_dialogue.script:loadFile("mod_assets/scripts/dialogues/dialogue_wizards.lua")
spawn("castle_ceiling_lantern",4,20,1,0,"castle_ceiling_lantern_1")
spawn("script_entity",0,1,2,0,"script_entity_6")
script_entity_6.script:loadFile("mod_assets/scripts/refresh.lua")
spawn("timer",1,1,1,0,"timer_1")
timer_1.timer:setTimerInterval(1)
timer_1.timer:setDisableSelf(false)
timer_1.timer:setTriggerOnStart(true)
timer_1.timer:setCurrentLevelOnly(false)
timer_1.timer:addConnector("onActivate", "script_entity_6", "refresh")
spawn("script_entity",15,12,3,0,"script_dialogue_03")
script_dialogue_03.script:loadFile("mod_assets/scripts/dialogues/dialogue_03.lua")
spawn("script_entity",16,12,2,0,"script_dialogue_04")
script_dialogue_04.script:loadFile("mod_assets/scripts/dialogues/dialogue_04.lua")
spawn("healing_crystal",21,14,3,0,"healing_crystal_2")
spawn("torch_holder",22,8,0,0,"torch_holder_21")
torch_holder_21.controller:setHasTorch(true)
spawn("torch_holder",23,8,2,0,"torch_holder_22")
torch_holder_22.controller:setHasTorch(true)
spawn("floor_trigger",23,8,1,0,"floor_trigger_10")
floor_trigger_10.floortrigger:setTriggeredByParty(true)
floor_trigger_10.floortrigger:setTriggeredByMonster(false)
floor_trigger_10.floortrigger:setTriggeredByItem(false)
floor_trigger_10.floortrigger:setTriggeredByDigging(false)
floor_trigger_10.floortrigger:setDisableSelf(true)
floor_trigger_10.floortrigger:addConnector("onActivate", "script_messages", "message9")
floor_trigger_10.floortrigger:addConnector("onActivate", "script_entity_8", "hook")
spawn("lock_round",21,4,1,0,"lock_round_1")
lock_round_1.lock:setOpenedBy("brass_key")
lock_round_1.lock:addConnector("onActivate", "dungeon_door_iron_4", "open")
spawn("dungeon_pressure_plate",27,2,1,0,"dungeon_pressure_plate_2")
dungeon_pressure_plate_2.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_2.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_2.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_2.floortrigger:addConnector("onToggle", "dungeon_door_iron_6", "toggle")
spawn("dungeon_door_iron",29,2,3,0,"dungeon_door_iron_6")
spawn("torch_holder",26,2,3,0,"torch_holder_23")
torch_holder_23.controller:setHasTorch(true)
spawn("rock",28,2,0,0,"rock_1")
spawn("floor_trigger",28,2,3,0,"floor_trigger_17")
floor_trigger_17.floortrigger:setTriggeredByParty(true)
floor_trigger_17.floortrigger:setTriggeredByMonster(false)
floor_trigger_17.floortrigger:setTriggeredByItem(false)
floor_trigger_17.floortrigger:setTriggeredByDigging(false)
floor_trigger_17.floortrigger:setDisableSelf(true)
floor_trigger_17.floortrigger:addConnector("onActivate", "script_messages", "message12")
spawn("turtle",17,20,3,0,"turtle_11")
spawn("torch_holder",17,20,0,0,"torch_holder_24")
torch_holder_24.controller:setHasTorch(true)
spawn("mummy",16,20,3,0,"mummy_10")
spawn("skeleton_trooper",18,20,3,0,"skeleton_trooper_5")
spawn("dungeon_stairs_up",13,2,3,0,"dungeon_stairs_up_4")
spawn("dungeon_stairs_up",10,3,1,0,"dungeon_stairs_up_3")
spawn("dungeon_door_wooden",23,8,3,0,"dungeon_door_wooden_3")
spawn("script_entity",23,7,0,0,"script_entity_8")
script_entity_8.script:loadFile("mod_assets/scripts/sleep.lua")
spawn("floor_trigger",22,8,1,0,"floor_trigger_21")
floor_trigger_21.floortrigger:setTriggeredByParty(true)
floor_trigger_21.floortrigger:setTriggeredByMonster(false)
floor_trigger_21.floortrigger:setTriggeredByItem(false)
floor_trigger_21.floortrigger:setTriggeredByDigging(false)
floor_trigger_21.floortrigger:setDisableSelf(true)
floor_trigger_21.floortrigger:addConnector("onActivate", "script_entity_8", "unHook")
floor_trigger_21.floortrigger:addConnector("onActivate", "script_messages", "message10")
floor_trigger_21.floortrigger:addConnector("onActivate", "script_entity_9", "hook")
spawn("dungeon_alcove",22,8,3,0,"dungeon_alcove_10")
spawn("borra",22,8,3,0,"borra_7")
dungeon_alcove_10.surface:addItem(borra_7.item)
spawn("dungeon_wall_text",23,8,0,0,"dungeon_wall_text_5")
dungeon_wall_text_5.walltext:setWallText("Press 'R' to sleep.")
spawn("dungeon_wall_text",21,2,1,0,"dungeon_wall_text_6")
dungeon_wall_text_6.walltext:setWallText("Use the key in the lock hole.")
spawn("dungeon_wall_text",23,3,0,0,"dungeon_wall_text_7")
dungeon_wall_text_7.walltext:setWallText("Press the button.")
spawn("dungeon_wall_text",25,3,0,0,"dungeon_wall_text_8")
dungeon_wall_text_8.walltext:setWallText("Pull the chain.")
spawn("dungeon_wall_text",28,2,0,0,"dungeon_wall_text_9")
dungeon_wall_text_9.walltext:setWallText("Put any object in the pressure plate.")
spawn("script_entity",23,6,0,0,"script_entity_9")
script_entity_9.script:loadFile("mod_assets/scripts/eat.lua")
spawn("dungeon_alcove",24,11,2,0,"dungeon_alcove_11")
spawn("potion_healing",24,11,2,0,"potion_healing_8")
dungeon_alcove_11.surface:addItem(potion_healing_8.item)
spawn("torch_holder",24,10,0,0,"torch_holder_38")
torch_holder_38.controller:setHasTorch(true)
spawn("torch_holder",27,11,1,0,"torch_holder_39")
torch_holder_39.controller:setHasTorch(true)
spawn("floor_trigger",27,13,3,0,"floor_trigger_16")
floor_trigger_16.floortrigger:setTriggeredByParty(true)
floor_trigger_16.floortrigger:setTriggeredByMonster(false)
floor_trigger_16.floortrigger:setTriggeredByItem(false)
floor_trigger_16.floortrigger:setTriggeredByDigging(false)
floor_trigger_16.floortrigger:setDisableSelf(true)
floor_trigger_16.floortrigger:addConnector("onActivate", "script_entity_9", "unHook")
floor_trigger_16.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_10", "close")
spawn("turtle",27,14,2,0,"turtle_12")
turtle_12.monster:setAIState("guard")
turtle_12.monster:addConnector("onDie", "dungeon_door_wooden_4", "open")
spawn("dungeon_ceiling_shaft",25,11,0,0,"dungeon_ceiling_shaft_2")
spawn("dungeon_ceiling_shaft",22,10,0,0,"dungeon_ceiling_shaft_3")
spawn("dungeon_door_portcullis",27,12,2,0,"dungeon_door_portcullis_10")
dungeon_door_portcullis_10.door:setDoorState("open")
spawn("dungeon_door_wooden",25,14,1,0,"dungeon_door_wooden_4")
spawn("mine_ceiling_lantern",27,14,3,0,"mine_ceiling_lantern_1")
spawn("ice_guardian",3,26,2,0,"ice_guardian_1")
ice_guardian_1.brain:disable()
spawn("medusa",5,26,2,0,"medusa_1")
medusa_1.brain:disable()
spawn("uggardian",4,26,2,0,"uggardian_1")
uggardian_1.brain:disable()
spawn("torch_holder",5,27,2,0,"torch_holder_40")
torch_holder_40.controller:setHasTorch(true)
spawn("torch_holder",3,27,2,0,"torch_holder_43")
torch_holder_43.controller:setHasTorch(true)
spawn("castle_door_portcullis",22,14,1,0,"castle_door_portcullis_1")
castle_door_portcullis_1.door:setDoorState("open")
spawn("grimtk",0,0,3,0,"grimtk_1")
grimtk_1.script:setSource("")
spawn("script_entity",22,12,1,0,"script_entity_3")
script_entity_3.script:loadFile("mod_assets/scripts/save.lua")
spawn("castle_door_portcullis",20,14,3,0,"castle_door_portcullis_2")
spawn("floor_trigger",19,14,2,0,"floor_trigger_18")
floor_trigger_18.floortrigger:setTriggeredByParty(true)
floor_trigger_18.floortrigger:setTriggeredByMonster(false)
floor_trigger_18.floortrigger:setTriggeredByItem(false)
floor_trigger_18.floortrigger:setTriggeredByDigging(false)
floor_trigger_18.floortrigger:setDisableSelf(false)
floor_trigger_18.floortrigger:addConnector("onActivate", "castle_door_portcullis_2", "close")
spawn("mine_ceiling_lantern",27,8,2,0,"mine_ceiling_lantern_2")
spawn("script_entity",17,12,1,0,"script_dialogue_05")
script_dialogue_05.script:loadFile("mod_assets/scripts/dialogues/dialogue_05.lua")
spawn("castle_ceiling_lantern",16,15,1,0,"castle_ceiling_lantern_3")
spawn("floor_trigger",16,14,0,0,"floor_trigger_22")
floor_trigger_22.floortrigger:setTriggeredByParty(true)
floor_trigger_22.floortrigger:setTriggeredByMonster(false)
floor_trigger_22.floortrigger:setTriggeredByItem(false)
floor_trigger_22.floortrigger:setTriggeredByDigging(false)
floor_trigger_22.floortrigger:setDisableSelf(false)
floor_trigger_22.floortrigger:addConnector("onActivate", "script_dialogue", "showDemoDialogue")
spawn("starting_location",3,12,0,0,"starting_location")
spawn("castle_door_portcullis",5,20,1,0,"castle_door_portcullis_3")
castle_door_portcullis_3.door:setDoorState("open")

--- level 2 ---

newMap{
	name = "B Level",
	width = 32,
	height = 32,
	levelCoord = {0,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,1,1,1,1,1,1,1,1,2,1,1,2,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("dungeon_stairs_up",5,20,3,0,"dungeon_stairs_up_1")
spawn("torch_holder",15,11,0,0,"torch_holder_3")
torch_holder_3.controller:setHasTorch(true)
spawn("dungeon_alcove",15,11,3,0,"dungeon_alcove_1")
spawn("dungeon_wall_broken_01",15,12,3,0,"dungeon_wall_broken_01_4")
spawn("dungeon_door_portcullis",16,12,2,0,"dungeon_door_portcullis_2")
dungeon_door_portcullis_2.door:setPullChain(true)
spawn("torch_holder",18,13,2,0,"torch_holder_1")
torch_holder_1.controller:setHasTorch(true)
spawn("dungeon_wall_broken_01",19,13,0,0,"dungeon_wall_broken_01_3")
spawn("dungeon_wall_broken_02",16,14,2,0,"dungeon_wall_broken_02_4")
spawn("torch_holder",21,14,1,0,"torch_holder_2")
torch_holder_2.controller:setHasTorch(true)
spawn("dungeon_wall_text",21,14,3,0,"dungeon_wall_text_1")
dungeon_wall_text_1.walltext:setWallText("Dungeon B")
spawn("dungeon_door_portcullis",21,14,2,0,"dungeon_door_portcullis_1")
dungeon_door_portcullis_1.door:setPullChain(true)
spawn("wall_button",17,16,3,0,"wall_button_1")
wall_button_1.button:setDisableSelf(false)
wall_button_1.button:addConnector("onActivate", "dungeon_door_portcullis_3", "open")
spawn("dungeon_wall_broken_02",22,16,1,0,"dungeon_wall_broken_02_5")
spawn("dungeon_wall_broken_02",13,17,3,0,"dungeon_wall_broken_02_1")
spawn("torch_holder",14,17,2,0,"torch_holder_4")
torch_holder_4.controller:setHasTorch(true)
spawn("dungeon_door_portcullis",15,17,3,0,"dungeon_door_portcullis_3")
dungeon_door_portcullis_3.door:setDoorState("open")
spawn("dungeon_wall_broken_01",15,17,0,0,"dungeon_wall_broken_01_5")
spawn("dungeon_pressure_plate",16,17,3,0,"dungeon_pressure_plate_1")
dungeon_pressure_plate_1.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_1.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_1.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_3", "close")
spawn("ceiling_witch_lantern",17,17,0,0,"ceiling_witch_lantern_3")
spawn("dungeon_alcove",19,17,3,0,"dungeon_alcove_2")
spawn("wooden_box",19,17,3,0,"wooden_box_1")
dungeon_alcove_2.surface:addItem(wooden_box_1.item)
spawn("ceiling_witch_lantern",19,17,1,0,"ceiling_witch_lantern_1")
spawn("dungeon_wall_broken_01",7,19,0,0,"dungeon_wall_broken_01_2")
spawn("ceiling_witch_lantern",7,20,1,0,"ceiling_witch_lantern_7")
spawn("altar",7,20,3,0,"altar_1")
spawn("dungeon_door_iron",11,20,3,0,"dungeon_door_iron_1")
spawn("lock",11,20,0,0,"lock_1")
lock_1.lock:setOpenedBy("iron_key")
lock_1.lock:addConnector("onActivate", "dungeon_door_iron_1", "open")
spawn("ceiling_witch_lantern",18,20,1,0,"ceiling_witch_lantern_4")
spawn("dungeon_secret_button_large",18,20,1,0,"dungeon_secret_button_large_1")
dungeon_secret_button_large_1.button:setDisableSelf(false)
dungeon_secret_button_large_1.button:addConnector("onActivate", "dungeon_secret_door_1", "open")
spawn("ceiling_witch_lantern",20,20,3,0,"ceiling_witch_lantern_2")
spawn("dungeon_wall_broken_01",10,21,2,0,"dungeon_wall_broken_01_1")
spawn("dungeon_wall_broken_02",12,21,2,0,"dungeon_wall_broken_02_2")
spawn("ceiling_witch_lantern",14,21,3,0,"ceiling_witch_lantern_5")
spawn("dungeon_secret_door",20,21,0,0,"dungeon_secret_door_1")
spawn("dungeon_wall_broken_02",15,22,1,0,"dungeon_wall_broken_02_3")
spawn("ceiling_witch_lantern",14,23,2,0,"ceiling_witch_lantern_6")
spawn("dungeon_alcove",14,23,0,0,"dungeon_alcove_3")
spawn("iron_key",14,23,0,0,"iron_key_1")
dungeon_alcove_3.surface:addItem(iron_key_1.item)
spawn("floor_trigger",20,11,0,0,"floor_trigger_14")
floor_trigger_14.floortrigger:setTriggeredByParty(true)
floor_trigger_14.floortrigger:setTriggeredByMonster(false)
floor_trigger_14.floortrigger:setTriggeredByItem(false)
floor_trigger_14.floortrigger:setTriggeredByDigging(false)
floor_trigger_14.floortrigger:setDisableSelf(true)
floor_trigger_14.floortrigger:addConnector("onActivate", "script_entity_4", "deactivateTeleport")
floor_trigger_14.floortrigger:addConnector("onActivate", "script_entity_10", "hook")
spawn("script_entity",20,10,0,0,"script_entity_4")
script_entity_4.script:setSource("function deactivateTeleport()\
\9findEntity(\"teleporter_blue\"):destroy()\
\9findEntity(\"healing_crystal_2\").crystal:activate();\
end")
spawn("turtle",15,12,1,0,"turtle_2")
turtle_2.monster:setAIState("guard")
spawn("turtle",21,16,0,0,"turtle_3")
turtle_3.monster:setAIState("guard")
spawn("turtle",20,17,2,0,"turtle_4")
turtle_4.monster:setAIState("guard")
spawn("turtle",18,18,0,0,"turtle_5")
turtle_5.monster:setAIState("guard")
spawn("turtle",14,19,0,0,"turtle_6")
turtle_6.monster:setAIState("guard")
spawn("skeleton_trooper",7,19,0,0,"skeleton_trooper_1")
skeleton_trooper_1.monster:setAIState("guard")
spawn("mummy",14,17,0,0,"mummy_1")
mummy_1.monster:setAIState("guard")
spawn("mummy",8,21,0,0,"mummy_2")
mummy_2.monster:setAIState("guard")
spawn("potion_healing",10,19,0,0,"potion_healing_2")
spawn("potion_healing",20,21,1,0,"potion_healing_3")
spawn("machete",16,10,0,0,"machete_1")
spawn("battle_axe",13,23,3,0,"battle_axe_1")
spawn("borra",16,14,3,0,"borra_2")
spawn("leather_boots",21,13,1,0,"leather_boots_1")
spawn("leather_pants",21,19,1,0,"leather_pants_2")
spawn("leather_brigandine",20,22,3,0,"leather_brigandine_2")
spawn("leather_cap",22,15,1,0,"leather_cap_3")
spawn("script_entity",21,10,1,0,"script_entity_10")
script_entity_10.script:loadFile("mod_assets/scripts/hookB.lua")

--- level 3 ---

newMap{
	name = "A Level",
	width = 32,
	height = 32,
	levelCoord = {1,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,1,1,1,1,1,1,1,1,2,1,1,2,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,1,1,1,1,1,2,1,1,1,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("torch_holder",18,13,2,0,"torch_holder_17")
torch_holder_17.controller:setHasTorch(true)
spawn("torch_holder",15,11,0,0,"torch_holder_18")
torch_holder_18.controller:setHasTorch(true)
spawn("torch_holder",21,14,1,0,"torch_holder_19")
torch_holder_19.controller:setHasTorch(true)
spawn("torch_holder",14,17,2,0,"torch_holder_20")
torch_holder_20.controller:setHasTorch(true)
spawn("dungeon_alcove",15,11,3,0,"dungeon_alcove_7")
spawn("dungeon_alcove",14,23,0,0,"dungeon_alcove_8")
spawn("iron_key",14,23,0,0,"iron_key_2")
dungeon_alcove_8.surface:addItem(iron_key_2.item)
spawn("dungeon_alcove",19,17,3,0,"dungeon_alcove_9")
spawn("wooden_box",19,17,3,0,"wooden_box_2")
dungeon_alcove_9.surface:addItem(wooden_box_2.item)
spawn("dungeon_wall_text",21,14,3,0,"dungeon_wall_text_3")
dungeon_wall_text_3.walltext:setWallText("Dungeon A")
spawn("dungeon_door_portcullis",16,12,2,0,"dungeon_door_portcullis_4")
dungeon_door_portcullis_4.door:setPullChain(true)
spawn("dungeon_door_portcullis",21,15,0,0,"dungeon_door_portcullis_5")
dungeon_door_portcullis_5.door:setPullChain(true)
spawn("dungeon_door_portcullis",14,17,1,0,"dungeon_door_portcullis_9")
dungeon_door_portcullis_9.door:setDoorState("open")
spawn("dungeon_door_iron",11,20,3,0,"dungeon_door_iron_5")
spawn("ceiling_witch_lantern",17,17,0,0,"ceiling_witch_lantern_8")
spawn("ceiling_witch_lantern",19,17,3,0,"ceiling_witch_lantern_9")
spawn("ceiling_witch_lantern",18,20,0,0,"ceiling_witch_lantern_10")
spawn("ceiling_witch_lantern",20,20,1,0,"ceiling_witch_lantern_11")
spawn("ceiling_witch_lantern",14,21,1,0,"ceiling_witch_lantern_12")
spawn("ceiling_witch_lantern",14,23,2,0,"ceiling_witch_lantern_13")
spawn("dungeon_secret_door",20,21,0,0,"dungeon_secret_door_2")
spawn("dungeon_secret_button_large",18,20,1,0,"dungeon_secret_button_large_2")
dungeon_secret_button_large_2.button:setDisableSelf(false)
dungeon_secret_button_large_2.button:addConnector("onActivate", "dungeon_secret_door_2", "open")
spawn("wall_button",17,16,3,0,"wall_button_3")
wall_button_3.button:setDisableSelf(false)
wall_button_3.button:addConnector("onActivate", "dungeon_door_portcullis_9", "open")
spawn("dungeon_pressure_plate",16,17,3,0,"dungeon_pressure_plate_4")
dungeon_pressure_plate_4.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByMonster(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByItem(true)
dungeon_pressure_plate_4.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_4.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_4.floortrigger:addConnector("onActivate", "dungeon_door_portcullis_9", "close")
spawn("lock",11,20,0,0,"lock_3")
lock_3.lock:setOpenedBy("iron_key")
lock_3.lock:addConnector("onActivate", "dungeon_door_iron_5", "open")
spawn("dungeon_wall_broken_01",7,19,0,0,"dungeon_wall_broken_01_6")
spawn("dungeon_wall_broken_01",10,21,2,0,"dungeon_wall_broken_01_7")
spawn("dungeon_wall_broken_01",15,12,3,0,"dungeon_wall_broken_01_8")
spawn("dungeon_wall_broken_01",19,13,0,0,"dungeon_wall_broken_01_9")
spawn("dungeon_wall_broken_02",16,14,2,0,"dungeon_wall_broken_02_6")
spawn("dungeon_wall_broken_02",22,16,1,0,"dungeon_wall_broken_02_7")
spawn("dungeon_wall_broken_02",13,17,3,0,"dungeon_wall_broken_02_8")
spawn("dungeon_wall_broken_01",15,17,0,0,"dungeon_wall_broken_01_10")
spawn("dungeon_wall_broken_02",12,21,2,0,"dungeon_wall_broken_02_9")
spawn("dungeon_wall_broken_02",15,22,1,0,"dungeon_wall_broken_02_10")
spawn("ceiling_witch_lantern",7,20,3,0,"ceiling_witch_lantern_14")
spawn("altar",7,20,3,0,"altar_2")
spawn("dungeon_stairs_up",5,20,3,0,"dungeon_stairs_up_2")
spawn("floor_trigger",20,11,3,0,"floor_trigger_15")
floor_trigger_15.floortrigger:setTriggeredByParty(true)
floor_trigger_15.floortrigger:setTriggeredByMonster(false)
floor_trigger_15.floortrigger:setTriggeredByItem(false)
floor_trigger_15.floortrigger:setTriggeredByDigging(false)
floor_trigger_15.floortrigger:setDisableSelf(true)
floor_trigger_15.floortrigger:addConnector("onActivate", "script_entity_5", "deactivateTeleport")
floor_trigger_15.floortrigger:addConnector("onActivate", "script_entity_11", "hook")
spawn("script_entity",20,10,3,0,"script_entity_5")
script_entity_5.script:setSource("function deactivateTeleport()\
\9findEntity(\"teleporter_red\"):destroy()\
\9findEntity(\"healing_crystal_2\").crystal:activate();\
end")
spawn("leather_brigandine",16,10,0,0,"leather_brigandine_3")
spawn("leather_pants",18,15,0,0,"leather_pants_3")
spawn("leather_cap",21,19,1,0,"leather_cap_1")
spawn("potion_healing",22,15,1,0,"potion_healing_4")
spawn("potion_healing",19,18,3,0,"potion_healing_5")
spawn("potion_healing",6,19,3,0,"potion_healing_6")
spawn("leather_boots",15,20,1,0,"leather_boots_3")
spawn("borra",16,14,1,0,"borra_3")
spawn("borra",17,18,2,0,"borra_4")
spawn("borra",12,21,1,0,"borra_5")
spawn("borra",7,21,2,0,"borra_6")
spawn("skeleton_trooper",8,19,2,0,"skeleton_trooper_2")
skeleton_trooper_2.monster:setAIState("guard")
spawn("skeleton_trooper",8,21,1,0,"skeleton_trooper_3")
skeleton_trooper_3.monster:setAIState("guard")
spawn("skeleton_trooper",13,23,0,0,"skeleton_trooper_4")
skeleton_trooper_4.monster:setAIState("guard")
spawn("mummy",10,20,3,0,"mummy_3")
mummy_3.monster:setAIState("guard")
spawn("mummy",15,21,2,0,"mummy_4")
mummy_4.monster:setAIState("guard")
spawn("mummy",13,19,0,0,"mummy_5")
mummy_5.monster:setAIState("guard")
spawn("mummy",18,20,0,0,"mummy_6")
mummy_6.monster:setAIState("guard")
spawn("mummy",20,19,0,0,"mummy_7")
mummy_7.monster:setAIState("guard")
spawn("mummy",20,21,0,0,"mummy_8")
mummy_8.monster:setAIState("guard")
spawn("mummy",15,11,2,0,"mummy_9")
mummy_9.monster:setAIState("guard")
spawn("turtle",16,12,2,0,"turtle_7")
turtle_7.monster:setAIState("guard")
spawn("turtle",16,13,1,0,"turtle_8")
turtle_8.monster:setAIState("guard")
spawn("turtle",18,16,0,0,"turtle_9")
turtle_9.monster:setAIState("guard")
spawn("turtle",21,17,0,0,"turtle_10")
turtle_10.monster:setAIState("guard")
spawn("potion_healing",20,22,2,0,"potion_healing_7")
spawn("machete",19,13,2,0,"machete_3")
spawn("battle_axe",13,17,2,0,"battle_axe_2")
spawn("script_entity",21,10,3,0,"script_entity_11")
script_entity_11.script:loadFile("mod_assets/scripts/hookA.lua")

--- level 4 ---

newMap{
	name = "A Exit",
	width = 32,
	height = 32,
	levelCoord = {1,0,-1},
	ambientTrack = "dungeon",
	tiles = {
		"castle_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("castle_stairs_down",6,20,1,0,"castle_stairs_down_1")
spawn("castle_ceiling_lantern",4,20,0,0,"castle_ceiling_lantern_2")
spawn("teleporter",2,20,3,0,"teleporter_2")
teleporter_2.teleporter:setTeleportTarget(1,21,13,0)
teleporter_2.teleporter:setSpin("none")
teleporter_2.teleporter:setTriggeredByParty(true)
teleporter_2.teleporter:setTriggeredByMonster(true)
teleporter_2.teleporter:setTriggeredByItem(true)
teleporter_2.teleporter:setTriggeredBySpell(true)
spawn("floor_trigger",3,20,2,0,"floor_trigger_13")
floor_trigger_13.floortrigger:setTriggeredByParty(true)
floor_trigger_13.floortrigger:setTriggeredByMonster(false)
floor_trigger_13.floortrigger:setTriggeredByItem(false)
floor_trigger_13.floortrigger:setTriggeredByDigging(false)
floor_trigger_13.floortrigger:setDisableSelf(true)
floor_trigger_13.floortrigger:addConnector("onActivate", "script_dialogue", "setRedTrue")
floor_trigger_13.floortrigger:addConnector("onActivate", "castle_door_portcullis_4", "close")
floor_trigger_13.floortrigger:addConnector("onActivate", "script_entity_11", "unHook")
spawn("castle_door_portcullis",5,20,1,0,"castle_door_portcullis_4")
castle_door_portcullis_4.door:setDoorState("open")

--- level 5 ---

newMap{
	name = "Maze",
	width = 32,
	height = 32,
	levelCoord = {0,0,-2},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,1,1,2,1,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,1,2,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,2,1,2,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("dungeon_stairs_down",9,3,3,0,"dungeon_stairs_down_1")
spawn("torch_holder",14,5,2,0,"torch_holder_25")
torch_holder_25.controller:setHasTorch(true)
spawn("torch_holder",19,1,0,0,"torch_holder_26")
torch_holder_26.controller:setHasTorch(true)
spawn("torch_holder",19,5,1,0,"torch_holder_27")
torch_holder_27.controller:setHasTorch(true)
spawn("torch_holder",12,2,3,0,"torch_holder_28")
torch_holder_28.controller:setHasTorch(true)
spawn("torch_holder",10,9,1,0,"torch_holder_29")
torch_holder_29.controller:setHasTorch(true)
spawn("floor_trigger",10,6,2,0,"floor_trigger_19")
floor_trigger_19.floortrigger:setTriggeredByParty(true)
floor_trigger_19.floortrigger:setTriggeredByMonster(false)
floor_trigger_19.floortrigger:setTriggeredByItem(false)
floor_trigger_19.floortrigger:setTriggeredByDigging(false)
floor_trigger_19.floortrigger:setDisableSelf(true)
floor_trigger_19.floortrigger:addConnector("onActivate", "script_entity_7", "message1")
spawn("floor_trigger",12,15,0,0,"floor_trigger_20")
floor_trigger_20.floortrigger:setTriggeredByParty(true)
floor_trigger_20.floortrigger:setTriggeredByMonster(false)
floor_trigger_20.floortrigger:setTriggeredByItem(false)
floor_trigger_20.floortrigger:setTriggeredByDigging(false)
floor_trigger_20.floortrigger:setDisableSelf(true)
floor_trigger_20.floortrigger:addConnector("onActivate", "script_entity_7", "message2")
spawn("script_entity",6,7,1,0,"script_entity_7")
script_entity_7.script:setSource("function message1()\
\9GTKGui.Basic.showInfoMessage(\"If you get lost press 'TAB' to open the map.\");\
end\
\
function message2()\
\9GTKGui.Basic.showInfoMessage(\"Don't forget to press 'TAB' to open the map.\", 5);\
end")
spawn("torch_holder",10,17,2,0,"torch_holder_31")
torch_holder_31.controller:setHasTorch(true)
spawn("torch_holder",19,17,1,0,"torch_holder_32")
torch_holder_32.controller:setHasTorch(true)
spawn("torch_holder",12,15,3,0,"torch_holder_33")
torch_holder_33.controller:setHasTorch(true)
spawn("torch_holder",19,13,1,0,"torch_holder_34")
torch_holder_34.controller:setHasTorch(true)
spawn("torch_holder",17,8,2,0,"torch_holder_35")
torch_holder_35.controller:setHasTorch(true)
spawn("torch_holder",17,11,2,0,"torch_holder_36")
torch_holder_36.controller:setHasTorch(true)
spawn("torch_holder",13,11,2,0,"torch_holder_37")
torch_holder_37.controller:setHasTorch(true)
spawn("dungeon_wall_text",10,3,1,0,"dungeon_wall_text_4")
dungeon_wall_text_4.walltext:setWallText("Labyrinth")
spawn("torch_holder",10,3,0,0,"torch_holder_30")
torch_holder_30.controller:setHasTorch(true)
spawn("dungeon_stairs_down",14,2,1,0,"dungeon_stairs_down_2")

--- level 6 ---

newMap{
	name = "End",
	width = 32,
	height = 32,
	levelCoord = {2,2,0},
	ambientTrack = "beach",
	tiles = {
		"beach_ground",
		"beach_ground_grass",
		"beach_ground_water",
		"beach_wall",
		"forest_ground",
		"forest_ground2",
		"forest_hedge",
	}
}

loadLayer("heightmap", {
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,3,3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,-2,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,-2,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,-1,0,-2,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,-1,-2,-2,-3,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,-1,-2,-2,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,-1,-1,-2,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,-1,-1,-2,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,-1,-1,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,-1,-1,-1,-1,-2,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,-1,-1,-2,-2,-2,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,-1,-2,-2,-3,-3,-3,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,-1,-2,-2,-2,-2,-3,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,-1,-1,-1,-1,-2,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,-1,-1,-2,-3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,-1,-2,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,-1,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,3,0,0,0,0,0,-1,-2,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,3,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,3,3,3,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
})

loadLayer("tiles", {
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,1,
	3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,6,6,1,1,3,3,3,3,3,3,4,7,7,7,
	3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,7,7,4,4,
	3,3,1,1,1,1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,1,1,1,1,1,3,3,7,7,4,4,1,
	3,3,3,1,1,1,6,6,6,6,6,5,5,6,6,6,6,6,6,6,6,1,1,1,1,7,7,7,4,4,1,1,
	3,3,3,1,1,1,6,6,5,5,5,6,6,5,5,6,6,6,6,6,6,6,1,1,7,7,4,4,4,4,1,1,
	3,3,3,1,1,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,6,1,7,7,4,4,1,4,1,1,1,
	3,3,1,1,1,6,6,6,6,6,5,5,6,6,6,6,6,6,6,6,5,1,7,7,4,1,1,1,1,1,1,1,
	3,3,3,1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,7,7,4,2,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,5,6,6,6,6,6,6,6,6,6,5,6,7,4,4,2,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,5,6,6,6,6,6,6,6,6,6,5,7,7,4,2,2,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,5,6,7,4,4,2,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,5,6,6,6,6,6,6,6,5,6,6,7,4,2,2,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,5,5,6,6,5,6,5,5,6,6,6,7,4,2,1,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,6,5,5,5,5,6,6,5,5,6,4,7,4,2,1,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,6,6,6,6,6,6,6,5,6,6,6,7,4,4,1,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,6,1,7,7,4,1,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,6,6,6,6,6,6,6,6,6,6,6,6,1,1,1,7,4,4,1,1,1,1,1,1,1,1,
	3,3,1,1,1,6,1,1,6,1,1,1,1,1,1,1,1,1,1,1,1,7,7,4,1,1,1,1,4,1,1,1,
	3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,7,7,4,4,4,1,4,4,1,1,
	3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,7,7,4,4,4,4,4,1,1,
	3,3,3,3,1,1,1,1,1,1,1,3,1,3,3,3,3,3,3,3,3,3,3,7,7,7,7,7,4,4,4,4,
	3,3,3,3,3,3,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,7,7,7,7,7,4,4,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,7,7,7,7,7,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
	3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
})

spawn("forest_heightmap",1,1,2,0,"forest_heightmap_1")
spawn("forest_day_sky",3,1,1,0,"forest_day_sky_1")
spawn("beach_ocean",23,15,3,0,"beach_ocean_1")
spawn("invisible_wall",31,16,0,0,"invisible_wall_1")
spawn("invisible_wall",31,17,0,0,"invisible_wall_2")
spawn("invisible_wall",31,18,2,0,"invisible_wall_3")
spawn("invisible_wall",31,19,2,0,"invisible_wall_4")
spawn("invisible_wall",31,20,1,0,"invisible_wall_5")
spawn("invisible_wall",30,17,2,0,"invisible_wall_6")
spawn("invisible_wall",30,18,0,0,"invisible_wall_7")
spawn("invisible_wall",30,18,2,0,"invisible_wall_8")
spawn("invisible_wall",30,19,1,0,"invisible_wall_9")
spawn("invisible_wall",31,9,1,0,"invisible_wall_11")
spawn("invisible_wall",31,10,3,0,"invisible_wall_12")
spawn("invisible_wall",31,11,2,0,"invisible_wall_13")
spawn("invisible_wall",30,10,2,0,"invisible_wall_14")
spawn("invisible_wall",30,11,1,0,"invisible_wall_15")
spawn("invisible_wall",29,17,3,0,"invisible_wall_16")
spawn("invisible_wall",28,17,1,0,"invisible_wall_17")
spawn("invisible_wall",31,12,0,0,"invisible_wall_10")
