-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom item definitions here

defineObject{
	name = "machete",
	baseObject = "base_item",
	components = {
		{
			class = "Model",
			model = "assets/models/items/machete.fbx",
		},
		{
			class = "Item",
			uiName = "Machete",
			gfxIndex = 23,
			impactSound = "impact_blade",
			weight = 2.2,
			traits = { "light_weapon", "sword" },
		},
		{
			class = "MeleeAttack",
			attackPower = 12,
			accuracy = 0,
			cooldown = 2.5,
			swipe = "horizontal",
		},
	},
	tags = { "weapon" },
}

defineObject{
	name = "battle_axe",
	baseObject = "base_item",
	components = {
		{
			class = "Model",
			model = "assets/models/items/battle_axe.fbx",
		},
		{
			class = "Item",
			uiName = "Battle Axe",
			gfxIndex = 86,
			gfxIndexPowerAttack = 460,
			impactSound = "impact_blade",
			weight = 4.0,
			traits = { "heavy_weapon", "axe" },
		},
		{
			class = "MeleeAttack",
			attackPower = 20,
			accuracy = 0,
			cooldown = 3.2,
			swipe = "horizontal",
			attackSound = "swipe",
			powerAttackTemplate = "chop",
		},
	},
	tags = { "weapon" },
}
