-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom dungeon object definitions here

defineObject{
   name = "party",
   baseObject = "party",
   components = {
      {
        class = "Party",
      onMove = function(party,dir,arg1)
         hudPrint(party.go.id .. "moving to" .. dir)
      end,
      -- WORKS
      onDie = function(party,champion)
         print(party.go.id,champion:getName(),'died')
				 party.party:heal()
      end,
      }
   },
}
